services:
  - type: web
    name: novnc
    runtime: docker
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: desktop-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: RESOLUTION
        value: 1280x800
      - key: VNC_PASSWORD
        sync: false
      - key: NGROK_AUTHTOKEN
        sync: false
