[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=Xvfb :0 -screen 0 1280x800 -ac +extension GLX +render -noreset
autorestart=true
priority=100

[program:x11vnc]
command=x11vnc -display :0 -rfbport 5900 -shared -forever -nopw -xkb
autorestart=true
priority=200

[program:xfce]
command=xfce4-session
environment=DISPLAY=":0",HOME="/home/desktopuser"
user=desktopuser
autorestart=true
priority=300

[program:websockify]
command=websockify --web /usr/share/novnc/ %(ENV_PORT)s localhost:5900
autorestart=true
priority=400

[program:flask]
command=python3 /app.py
autorestart=true
priority=500
