#!/bin/bash
set -e

CPUS="${CPU_COUNT:-$(nproc 2>/dev/null || echo 1)}"
[[ "${CPUS}" =~ ^[0-9]+$ ]] || CPUS=1
if [ "${CPUS}" -lt 1 ]; then CPUS=1; fi

exec /usr/bin/google-chrome \
    --no-sandbox \
    --test-type \
    --disable-gpu \
    --disable-dev-shm-usage \
    --password-store=basic \
    --no-first-run \
    --no-default-browser-check \
    --disable-background-timer-throttling \
    --disable-backgrounding-occluded-windows \
    --disable-renderer-backgrounding \
    --num-raster-threads="${CPUS}" \
    "$@"
